# Generated by Django 3.0 on 2021-05-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='alias',
        ),
        migrations.AddField(
            model_name='document',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
