# Generated by Django 3.2.3 on 2021-05-23 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_auto_20210523_0619'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='odoo_id',
            field=models.IntegerField(default=0),
        ),
    ]
