# Generated by Django 3.2.3 on 2021-05-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_document_odoo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='mime_type',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
