# Generated by Django 3.2.3 on 2021-05-23 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_document_mime_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='mime_type',
            new_name='mimetype',
        ),
    ]
