# Generated by Django 3.2.3 on 2021-05-24 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_document_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odoo',
            name='odoo_url',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
