# Generated by Django 3.2.3 on 2021-05-24 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_ocrelement_ocrelementpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocrelement',
            name='text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
