# Generated by Django 3.2.3 on 2021-05-24 11:34

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_auto_20210524_1044'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Point',
        ),
        migrations.DeleteModel(
            name='Polygon',
        ),
        migrations.AddField(
            model_name='ocrelement',
            name='rectangle',
            field=django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326),
        ),
    ]
