# Generated by Django 3.2.3 on 2021-05-24 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0014_auto_20210524_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='res_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='res_model',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
